### ISSUE TITLE
question

### ISSUE THREAD

**Issue by wear-crown** [lunarwhite/covid19-sentiment-data-analysis#1]
请问100天情感折线图的数据怎么算出来的

**Comment by smallrain520** [comment]
你好，，为啥我爬虫运行的时候没法生成对应的文件怎么回事，，还有day is out range of month

**Comment by lunarwhite** [comment]
无法生成对应的文件，可能：
1. 未修改本地参数，比如cookie值
2. 目标网站的api有变动，需要修改相应逻辑

`day is out range of month`，可能：
- Python ValueError，检查一下月份与天数的对应关系

**Comment by smallrain520** [comment]
那你目前还能运行么




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yuedong ***@***.***&gt;; 
发送时间: 2022年4月28日(星期四) 晚上8:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lunarwhite/covid19-sentiment-data-analysis] question (#1)





 
无法生成对应的文件，可能：
  
未修改本地参数，比如cookie值
 
目标网站的api有变动，需要修改相应逻辑
  
day is out range of month，可能：
  
Python ValueError，检查一下月份与天数的对应关系
